### ISSUE TITLE
Syntax error with "step" time unit

### ISSUE THREAD

**Issue by cmarqu** [chipsalliance/verible#1225]
Using current `master` (verible-v0.0-1959-gd9b88c73).

**Test case**

```systemverilog
#0step;
```

**Actual output**

```
lexical error, rejected "0step" (syntax-error).
```

**Comment by rfdonnelly** [comment]
Verible is doing the right thing there.  `0step` is not a valid SystemVerilog delay value.  `1step` is the only valid delay value for the *step* delay unit.  Here's the BNF from the 1800-2017 standard:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/28975/160259896-6c9d8456-a400-4e34-9214-1677a7dac04e.png">

You probably want `#0` instead of `#0step`.
