### ISSUE TITLE
Add clang-format and clang-tidy check in pull requests

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/verible#653]
Let's add another check to the presubmit checks: run all modified/new c++ files through `clang-format --style=Google` and report back if there is a diff. Similarly `clang-tidy` (need to figure out all useful options).

Show a diff and ask the user to run clang-format/clang-tidy locally on the code and update the pull request in that case.

(We have to report and can probably not update the pull request in-place with clang-format, because that might mess with a WIP pull request.)

**Comment by hzeller** [comment]
But maybe we could just run `clang-format` as a hook at time of merge ? That way, we don't have to bother the contributor with an insignificant technicality (we could still make this a pull request check, but not a merge-blocking one).

In the past operating model we were actually [doing this](https://github.com/google/verible/blob/b343939bb233786cca3469134c414ca40312fdfc/CONTRIBUTING.md#style), but we have to build out these things without the additional round-trip.

**Comment by mithro** [comment]
@hzeller -- I believe there are github actions that can be set up which will add a patch onto people's pull requests with the reformatting (or maybe just a set of suggestions?).

**Comment by mithro** [comment]
@umarcor -- Thoughts?

**Comment by umarcor** [comment]
It is technically possible to have a GitHub Actions workflow/job which interacts with either git or the GitHUb API for:

- Editing the original message in the PR.
- Posting a comment in the PR, or editing an already posted comment by the bot.
- Committing to the PR or to any other repository anywhere.

However, the scope of the default token is limited, and it does not suffice for pushing commits on top of existing PRs from forks. It will only work for PRs created from feature branches in this same repo.

Updating any PR would require the Personal Access Token of some maintainer to be added as a CI secret. That is undesirable, because then the scope is too wide and it's a potential security issue.

I would recommend avoiding having PRs updated automatically through this mechanism. If code style is considered code quality, IMHO it should be a regular job that fails. Contributors should take care of running clang-format and clang-tidy (through a hook, if they want to). Alternatively, if the style is not considered critical, I would not add any CI check, and just let maintainers reformat periodically.

**Comment by mithro** [comment]
BTW -- GitHub has a way to "suggesting" changes in a comment that the owner of the pull request can accept.

**Comment by umarcor** [comment]
It has. However, I think that each suggested change is saved as a different commit. It makes squashing almost a requirement... I find it desirable instead for CI to fail and contributors to run formatting locally.

**Comment by hzeller** [comment]
Yes, I think having a simple CI test that fails will be a simple and robust way to deal with this. It also allows the contributor to do everything on their machine with a one-liner which is much more comfortable than clicking many buttons in a browser.

**Comment by hzeller** [comment]
`clang-format` is covered. Remains `clang-tidy` to run on a pull request.
For this, `clang-tidy` needs a [compilation database](https://clang.llvm.org/docs/JSONCompilationDatabase.html), essentially containing compiler invocation parameters for the files involved.

It looks like [bazel]() does not support this (yet?) natively (I think), but there is some  IDE integration https://blog.bazel.build/2016/06/10/ide-support.html bridge code. Also there is the output of `bazel build -s ...` that could probably be used.

This project looks promising: https://github.com/grailbio/bazel-compilation-database : it provides a bazel rule to generate a compilation database, though it looks like it requires to list all the cc library rules ? Anyway looks like a good starting point.

**Comment by tgorochowik** [comment]
BTW Verilator does this, it creates an extra commit:
https://github.com/verilator/verilator/blob/36eb952b60239e0f42a055622b8273cabc6e1c84/.github/workflows/clang-format.yml
I think the permission problem is solved if such commits are pushed after the PR is merged (so creating PRs from different organizations is not a problem)

This is probably not the prettiest solution due to a bunch of reformatting commits in the master branch (e.g. https://github.com/verilator/verilator/commit/7bce15b065c2c305f39168c2b9ae0d28fa5ee801), but it seems to be a low-maintenance solution that just works.
